# Generated by Django 2.0.5 on 2018-05-09 05:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrequest',
            name='description',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testrequest',
            name='errors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=None, size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testrequest',
            name='failures',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=None, size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testrequest',
            name='template',
            field=models.CharField(default='Web Application', max_length=20),
        ),
    ]
